default_language_version:
  python: python3.14

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/crate-ci/typos
    rev: v1.44.0
    hooks:
      - id: typos

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.18.1
    hooks:
      - id: pyproject-fmt

  - repo: https://github.com/ulgens/uv-lock-check
    rev: v0.1.0
    hooks:
      - id: uv-lock-check
        language: python
        additional_dependencies:
          - uv==0.9.18

  - repo: https://github.com/rstcheck/rstcheck
    rev: v6.2.5
    hooks:
      - id: rstcheck

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.5
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/ulgens/ruffen-docs
    rev: 1def1ebbc1bd7f6b9934121948d0d06515f71e3f
    hooks:
      - id: blacken-docs
        language: python
        additional_dependencies:
          - black==26.3.1
        files: \.rst$

      - id: ruffen-docs-check
        language: python
        additional_dependencies:
          - ruff==0.14.10
        files: \.rst$

      - id: ruffen-docs-format
        language: python
        additional_dependencies:
          - ruff==0.14.10
        files: \.rst$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        language: python
        additional_dependencies:
          - black==26.3.1
          - pytest==9.0.2

  - repo: https://github.com/google/yamlfmt
    rev: v0.21.0
    hooks:
      - id: yamlfmt
